# Generated by Django 3.1.3 on 2021-04-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=2000)),
                ('g_id', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('goal', models.ForeignKey(blank=True, db_column='goal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='milestones_app.milestone')),
            ],
        ),
    ]
