# Generated by Django 3.1.3 on 2021-05-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0005_auto_20210501_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.TextField(max_length=2000),
        ),
    ]
