# Generated by Django 3.1.3 on 2021-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0006_auto_20210501_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
