# Generated by Django 3.1.3 on 2021-05-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0007_auto_20210501_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='color_id',
        ),
        migrations.AddField(
            model_name='goal',
            name='color_id',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
