# Generated by Django 3.1.3 on 2021-05-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0008_auto_20210502_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='color_id',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=33),
        ),
    ]
