# Generated by Django 3.1.3 on 2021-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0009_auto_20210502_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='color_id',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='goal',
            name='color_id',
            field=models.CharField(choices=[('0', 'Lavender'), ('1', 'Sage'), ('2', 'Grape'), ('3', 'Flamingo'), ('4', '\tBanana'), ('5', 'Tangerine'), ('6', 'Peacock'), ('7', '\tGraphite'), ('8', 'Blueberry'), ('9', 'Basil'), ('10', 'Tomato')], max_length=33),
        ),
    ]
