# Generated by Django 3.1.3 on 2021-05-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0010_auto_20210502_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='color_id',
            field=models.CharField(choices=[('0', 'who knows'), ('1', 'Lavender'), ('2', 'Sage'), ('3', 'Grape'), ('4', 'Flamingo'), ('5', '\tBanana'), ('6', 'Tangerine'), ('7', 'Peacock'), ('8', '\tGraphite'), ('9', 'Blueberry'), ('10', 'Basil'), ('11', 'Tomato')], max_length=33),
        ),
    ]
