# Generated by Django 3.1.3 on 2021-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0012_auto_20210503_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='color_id',
            field=models.CharField(choices=[('0', 'who knows'), ('1', 'Lavender'), ('2', 'Sage'), ('3', 'Grape'), ('4', 'Flamingo'), ('5', '\tBanana'), ('6', 'Tangerine'), ('7', 'Peacock'), ('8', '\tGraphite'), ('9', 'Blueberry'), ('10', 'Basil'), ('11', 'Tomato')], default='0', max_length=33),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='start',
            field=models.DateTimeField(blank=True, default='2021-05-10T08:30:50.855388', null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='text',
            field=models.TextField(blank=True, default='Why I chose this to be my first Milestone:', max_length=2000, null=True),
        ),
    ]
