# Generated by Django 3.1.3 on 2021-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones_app', '0013_auto_20210510_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='start',
            field=models.DateTimeField(blank=True, default='2021-05-17T09:17:39.333650', null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='text',
            field=models.TextField(blank=True, default='any Note?', max_length=2000, null=True),
        ),
    ]
